routes/web.php
<?php

use App\Http\Controllers\AdminAuth\LoginController;;
use App\Http\Controllers\AdminControllers\AdminDashboardController;
use App\Http\Controllers\AdminControllers\AdminSettingController;
use App\Http\Controllers\AdminControllers\RequestController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CreditCardController;
use App\Http\Controllers\MedicineController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\InventorySearchController;
use App\Http\Controllers\MobileBankController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RequestController as FeedbackController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\ShopRegistrationController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\SubscriptionHistoryController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth', 'subcheck', 'noticount']], function () {

    //Retailer Specific Routes Start
    Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
    Route::put('/cart', [CartController::class, 'store']);
    Route::delete('/cart/{itemid}', [CartController::class, 'destroy'])->whereNumber('itemid')->name('cart.remove');

    Route::post('/inventory/search/retailer', [InventorySearchController::class, 'retailerInventorySearch'])->name('inventory.search.retailer');

    Route::get('/onlineorder', [OrderController::class, 'index'])->name('order.index');
    Route::get('/ordercheckout', [OrderController::class, 'create'])->name('order.checkout');
    Route::put('/ordercheckout', [OrderController::class, 'store']);
    Route::get('/quickorder/{medicineName}', [OrderController::class, 'quickOrder'])->name('order.quick');

    Route::get('/sales', [SaleController::class, 'index'])->name('sales.index');
    Route::get('/sales/newsale', [SaleController::class, 'create'])->name('sales.newsale');
    Route::post('/sales/newsale', [SaleController::class, 'store']);
    Route::post('/search', [SearchController::class, 'search']);
    //Retailer Specific Routes End

    //Distributor Specific Routes Start
    Route::post('order/status', [OrderController::class, 'update']);

    Route::post('/settings/mobileaccount', [SettingController::class, 'saveMobileAccountSettings'])->name('setting.mobileaccountsave');
    Route::delete('/settings/mobileaccount', [MobileBankController::class, 'destroy']);
    //Distributor Specific Routes End

    //Common Routes Start
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('/inventory', InventoryController::class);

    Route::get('/medicine/{id}/detail/{distributorid}', [MedicineController::class, 'show'])->whereNumber(['id', 'distributorid']);

    Route::get('/notifications', [NotificationController::class, 'index'])->name('notification.index');
    Route::put('/notification/read/{id}', [NotificationController::class, 'update'])->name('notification.read');
    Route::delete('/notification/delete/{id}', [NotificationController::class, 'destroy'])->name('notification.delete');

    Route::get('/order/history',[OrderController::class, 'show'])->name('orderhistory.show');

    Route::get('/reports', [ReportController::class, 'index'])->name('report.index');
    Route::post('/reports/daily', [ReportController::class, 'reportsByDaily'])->name('reports.daily');
    Route::post('/reports/weekly', [ReportController::class, 'reportsByWeekly'])->name('reports.weekly');
    Route::post('/reports/monthly', [ReportController::class, 'reportsByMonthly'])->name('reports.monthly');
    Route::post('/reports/yearly', [ReportController::class, 'reportsByYearly'])->name('reports.yearly');
    Route::resource('/request', FeedbackController::class)->except(['index', 'edit', 'destroy', 'update']);
    Route::put('/request/{id}', [FeedbackController::class, 'updateUser'])->name('request.update');

    Route::resource('/shopregistration', ShopRegistrationController::class);
    Route::resource('/subscription', SubscriptionController::class)->withoutMiddleware('subcheck')->middleware('subselect');
    Route::get('/subscriptionhistory', [SubscriptionHistoryController::class, 'index'])->withoutMiddleware('subcheck')->name('subscriptionhistory.index');
    Route::get('/settings', [SettingController::class, 'index'])->withoutMiddleware('subcheck')->name('settings.index');
    Route::post('/settings/api/token/regenerate', [SettingController::class, 'regenerateApiToken'])->name('api.token.regenerate');
    Route::post('/settings/shopaddress', [SettingController::class, 'updateShopAddress'])->name('setting.shopaddress');
    Route::post('/settings/reapplied', [SettingController::class, 'reapply'])->withoutMiddleware('subcheck')->name('settings.reapply');
    Route::post('/settings/changepassword', [SettingController::class, 'changePassword'])->name('settings.changepassword');
    Route::post('/settings/creditcard', [CreditCardController::class, 'update'])->name('settings.creditcard');
    Route::delete('/settings/creditcard', [CreditCardController::class, 'destroy']);
    Route::post('/settings/contactnumber', [SettingController::class, 'updateContactNumber'])->name('setting.contactnumber');
    //Common Routes End
});

//Defining Admin Routes
Route::prefix('/admin')->name('admin.')->group(function () {
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('/login', [LoginController::class, 'login']);

    Route::middleware(['auth:admin', 'noticount'])->group(function(){
        Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');

        Route::get('/medicine/create', [MedicineController::class, 'create'])->name('medicine.create');
        Route::post('/medicine/create', [MedicineController::class, 'store']);
        Route::get('/medicine', [MedicineController::class, 'index'])->name('medicine.index');
        Route::get('/medicine/edit/{id}', [MedicineController::class, 'edit'])->name('medicine.edit');
        Route::put('/medicine/edit/{id}', [MedicineController::class, 'update']);
        Route::delete('/medicine/delete/{id}', [MedicineController::class, 'destroy'])->name('medicine.delete');

        Route::get('/subscriptions', [SubscriptionController::class, 'adminindex'])->name('subscription.index');
        Route::get('/subscriptions/create', [SubscriptionController::class, 'create'])->name('subscription.create');
        Route::post('/subscriptions/create', [SubscriptionController::class, 'store']);
        Route::get('/subscriptions/edit/{id}', [SubscriptionController::class, 'edit'])->name('subscription.edit');
        Route::post('/subscriptions/edit/{id}', [SubscriptionController::class, 'adminUpdate']);

        Route::get('/pendingrequests', [RequestController::class, 'index'])->name('pending.index');
        Route::get('/feedbacks', [FeedbackController::class, 'index'])->name('feedback.index');
        Route::get('/feedback/{id}', [FeedbackController::class, 'show'])->name('feedback.show');
        Route::put('/feedback/{id}', [FeedbackController::class, 'update'])->name('feedback.update');
        Route::put('/feedback/{id}/completed', [FeedbackController::class, 'changeStatus'])->name('feedback.completed');
        Route::put('/request/accepted/{userid}', [RequestController::class, 'update'])->name('request.accepte');
        Route::delete('/request/rejected/{userid}', [RequestController::class, 'destroy'])->name('request.rejected');
        Route::get('/settings', [AdminSettingController::class, 'index'])->name('settings.index');
        Route::post('/settings/changepassword', [AdminSettingController::class, 'updatePassword'])->name('settings.changepassword');
        Route::post('/settings/mobileaccount', [AdminSettingController::class, 'saveMobileAccountSettings'])->name('settings.mobileaccountsave');
    });
});

?>

resources/views/admin/main/allmedicines.blade.php
@extends('layouts.admin')

@section('content')
    <div class="jumbotron p-3">
        <div class="row">
            <div class="col-md-10">
                <span class="h1 d-block">Medicines</span>
            </div>
            <div class="p-2 col-md-2 d-flex align-items-middle justify-content-end">
                <span>
                    <a href="{{route('admin.medicine.create')}}" class="btn btn-success">Add New Medicine</a>
                </span>
            </div>
        </div>
    </div>

    @include('svgarts.empty', ['count' => !count($medicines)])

    <div class="container p-0">
        @foreach ($medicines as $medicine)
            <div class="jumbotron p-3 mb-1">
                <div class="row">
                    <div class="col-md-2">
                        <span class="h5 d-block">{{$medicine->MedicineId}}</span>
                        <span class="h6 d-block text-muted">Medicine Id</span>
                    </div>
                    <div class="col-md-2">
                        <span class="h5 d-block">{{$medicine->MedicineName}}</span>
                        <span class="h6 d-block text-muted">Medicine Name</span>
                    </div>
                    <div class="col-md-2">
                        <span class="h5 d-block">{{$medicine->MedicineCompany}}</span>
                        <span class="h6 d-block text-muted">Company</span>
                    </div>
                    <div class="col-md-2">
                        <span class="h5 d-block">{{$medicine->MedicineType}}</span>
                        <span class="h6 d-block text-muted">Type</span>
                    </div>
                    <div class="col-md-2">
                        <span class="h5 d-block">{{implode(',', json_decode($medicine->MedicineFormula))}}</span>
                        <span class="h6 d-block text-muted">Formula/Contains</span>
                    </div>
                    <div class="col-md-2">
                          <form class="d-none" method="POST" action="{{route('admin.medicine.delete', [$medicine->MedicineId])}}">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger float-right mt-2" href="#nolink"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                              </svg></button>
                          </form>
                          <a class="btn btn-primary float-right mr-2 mt-2" href="{{route('admin.medicine.edit', [$medicine->MedicineId])}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                          </svg></a>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/admin/main/allsubscriptionpackages.blade.php
@extends('layouts.admin')

@section('content')
    <div class="jumbotron p-3">
        <div class="row">
            <div class="col-md-10">
                <span class="h1 d-block">Subscription Packages</span>
            </div>
            <div class="p-2 col-md-2 d-flex align-items-middle justify-content-end">
                <span>
                    <a href="{{route('admin.subscription.create')}}" class="btn btn-success">Add New Package</a>
                </span>
            </div>
        </div>
    </div>

    @include('svgarts.empty', ['count' => !count($packages)])

    <div class="container p-0">
        @foreach ($packages as $package)
            <div class="jumbotron p-3 mb-1">
                <div class="row">
                    <div class="col-md-3">
                        <span class="h5 d-block">{{$package->PackageId}}</span>
                        <span class="h6 d-block text-muted">Package Id</span>
                    </div>
                    <div class="col-md-2">
                        <span class="h5 d-block">{{$package->PackageName}}</span>
                        <span class="h6 d-block text-muted">Name</span>
                    </div>
                    <div class="col-md-2">
                        <span class="h5 d-block">{{$package->PackagePrice}}</span>
                        <span class="h6 d-block text-muted">Price</span>
                    </div>
                    <div class="col-md-2">
                        <span class="h5 d-block">{{$package->PackageDuration}}</span>
                        <span class="h6 d-block text-muted">Duration (Month(s))</span>
                    </div>
                    <div class="col-md-3">
                        <a class="btn btn-primary float-right mr-2 mt-2" href="{{route('admin.subscription.edit', $package->PackageId)}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                        </svg></a>
                </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/admin/main/editsubscriptionpackage.blade.php
@extends('layouts.admin')

@section('content')
<div class="jumbotron p-3 mb-3">
    <span class="h1 d-block">Edit Subscription Package</span>
</div>
<div class="container-fluid p-3 overflow-auto">
        <div class="row mb-2 justify-content-center">
                <div class="col-md-6 pr-0">
                    <form id="form1" method="POST" action="{{route('admin.subscription.edit', $package->PackageId)}}">
                        @csrf
                        <input type="hidden" name="supportapi" value="0">

                        <div class="jumbotron p-2 bg-transparent border border-secondary">
                            <span class="d-block h5">Basic Details</span>
                            <hr>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">Package Name</span>
                                </div>
                                <input type="text" id="medname" name="pkgname" class="form-control" value="{{$package->PackageName}}">
                            </div>

                            <div class="input-group mt-2">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">Package Price</span>
                                </div>
                                <input type="number" min="0" pattern="[0-9]+" step="0.5" id="medcompany" name="pkgprice" class="form-control" value="{{$package->PackagePrice}}">
                            </div>

                            <div class="input-group mt-2">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">Package Duration</span>
                                </div>
                                <input type="number" min="0" pattern="[0-9]+" id="medcompany" name="pkgduration" class="form-control" value="{{$package->PackageDuration}}">
                            </div>

                            <span class="d-block h5 mt-3">Options</span>
                            <hr>
                            <div class="row">
                                <div class="col-md-12">
                                    <span class="float-left h6">Support API</span>
                                    <span class="float-right">
                                        <input type="checkbox" name="supportapi" value="1" @if($package->supportApi){{"checked"}}@endif>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
        </div>

        <div class="row">
            <div class="col-md-12 p-0">
                <button id="submitbtn" class="btn btn-success">Save Changes</button>
                <a href="{{route('admin.subscription.index')}}" class="btn btn-danger float-right">Discard</a>
            </div>
        </div>
</div>
<script>
    document.getElementById('submitbtn').addEventListener('click', function(){
        document.getElementById('form1').submit();
    });
</script>
@endsection

resources/views/admin/main/pendingrequest.blade.php
@extends('layouts.admin')

@section('content')
    <div class="jumbotron p-3">
        <span class="h1 d-block">Pending Requests</span>
    </div>

    @include('svgarts.empty', ['count' => !count($pendings)])

    <div class="container p-0">
        @foreach ($pendings as $pending)
            <div class="jumbotron p-3 mb-1">
                <div class="row">
                    <div class="col-md-2">
                        <span class="h5 d-block">{{$pending->id}}</span>
                        <span class="h6 d-block text-muted">User Id</span>
                    </div>
                    <div class="col-md-2">
                        <span class="h5 d-block">{{$pending->name}}</span>
                        <span class="h6 d-block text-muted">User Name</span>
                    </div>
                    <div class="col-md-3">
                        <span class="h5 d-block">{{$pending->email}}</span>
                        <span class="h6 d-block text-muted">User Email</span>
                    </div>
                    <div class="col-md-2">
                        <span class="h5 d-block">{{$pending->AccountStatus}}</span>
                        <span class="h6 d-block text-muted">Status</span>
                    </div>
                    <div class="col-md-2">
                        <span class="h5 d-block">{{$pending->created_at}}</span>
                        <span class="h6 d-block text-muted">Account Created</span>
                    </div>
                    <div class="col-md-1">
                        <div class="row d-block d-md-none">
                            {{-- It will display on small screens --}}
                            <div class="col-sm-12">
                                <form class="float-right" method="POST" action="#">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger" href="#nolink"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                        </svg></button>
                                </form>
                                <form method="POST" action="{{route('admin.request.accepte', [$pending->id])}}">
                                    @csrf
                                    @method('PUT')
                                    <button type="submit" class="btn btn-primary" href="#nolink">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check2" viewBox="0 0 16 16">
                                            <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
                                        </svg>
                                    </button>
                                </form>
                            </div>
                        </div>
                        <div class="row text-right d-none d-md-block">
                            {{-- It will display on screens from md to xxl --}}
                            <div class="col-md-12">
                                <form class="d-inline" method="POST" action="{{route('admin.request.rejected', [$pending->id])}}">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger" href="#nolink"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                        </svg></button>
                                    </form>
                            </div>
                        </div>
                        <div class="row text-right mt-1 d-none d-md-block">
                            {{-- It will display on screens from md to xxl --}}
                            <div class="col-md-12">
                                <form class="d-inline" method="POST" action="{{route('admin.request.accepte', [$pending->id])}}">
                                    @csrf
                                    @method('PUT')
                                    <button type="submit" class="btn btn-primary" href="#nolink">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check2" viewBox="0 0 16 16">
                                            <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
                                        </svg>
                                    </button>
                                    </form>
                            </div>
                        </div>
                </div>
                </div>
                <div class="row mt-2">
                    <div class="col-md-12">
                        <button class="btn btn-secondary btn-block" id="detailbtn-{{$pending->id}}">Show Details</button>
                    </div>
                </div>
                <div class="row mt-2 d-none" id="list-{{$pending->id}}">
                    <div class="col-md-6">
                        <div class="jumbotron p-2 text-center">
                            <span class="h5 mb-1">Cnic Front Picture</span>
                            <img class="d-block m-auto rounded" src="{{asset('storage/cnic/front/' . $pending->CnicFrontPic)}}" alt="No Image Found" height="200px" width="400px">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="jumbotron p-2 text-center">
                            <span class="h5 mb-1">Liscence Picture</span>
                            <img class="d-block m-auto rounded" src="@if($pending->UserType == 'Retailer'){{asset('storage/retailer/liscence/' . $pending->retailershop->LiscenceFrontPic)}}@elseif($pending->UserType == 'Distributor'){{asset('storage/distributor/liscence/' . $pending->distributorshop->LiscenceFrontPic)}}@endif" alt="No Image Found" height="200px" width="400px">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <hr class="divider bg-danger">
                        <span class="h3 d-block text-center">Details</span>
                        <hr class="divider">
                        <span class="d-block">
                            <span class="h4">Cnic#</span>
                            <span class="h5 float-right">{{$pending->CnicCardNumber}}</span>
                            <hr class="divider">
                        </span>
                        @if ($pending->UserType == 'Retailer')
                            <span class="d-block">
                                <span class="h4">Liscence#</span>
                                <span class="h5 float-right">{{$pending->retailershop->LiscenceNo}}</span>
                                <hr class="divider">
                            </span>

                            <span class="d-block">
                                <span class="h4">Shop Name: </span>
                                <span class="h5 float-right">{{$pending->retailershop->RetailerShopName}}</span>
                                <hr class="divider">
                            </span>

                            <span class="d-block">
                                <span class="h4">Shop Address: </span>
                                <span class="h5 float-right">{{$pending->retailershop->shopAddress}}</span>
                                <hr class="divider">
                            </span>

                            <span class="d-block">
                                <span class="h4">Contact# </span>
                                <span class="h5 float-right">{{$pending->retailershop->ContactNumber}}</span>
                            </span>

                            <span class="h3 d-block text-center">Subscription Details</span>
                            <hr class="divider">

                            <span class="d-block">
                                <span class="h4">Subscribed Package </span>
                                <span class="h5 float-right">{{$pending->retailershop->subscription->package->PackageName}}</span>
                                <hr class="divider">
                            </span>

                            <span class="d-block">
                                <span class="h4">Transaction Id# </span>
                                <span class="h5 float-right">{{$pending->retailershop->subscription->TransactionId}}</span>
                                <hr class="divider">
                            </span>

                            <span class="d-block">
                                <span class="h4">Payment Method </span>
                                <span class="h5 float-right">{{$pending->retailershop->subscription->PaymentMethod}}</span>
                            </span>
                        @elseif($pending->UserType == 'Distributor')
                            <span class="d-block">
                                <span class="h4">Liscence#</span>
                                <span class="h5 float-right">{{$pending->distributorshop->LiscenceNo}}</span>
                                <hr class="divider">
                            </span>

                            <span class="d-block">
                                <span class="h4">Shop Name: </span>
                                <span class="h5 float-right">{{$pending->distributorshop->DistributorShopName}}</span>
                                <hr class="divider">
                            </span>

                            <span class="d-block">
                                <span class="h4">Shop Address: </span>
                                <span class="h5 float-right">{{$pending->distributorshop->shopAddress}}</span>
                                <hr class="divider">
                            </span>

                            <span class="d-block">
                                <span class="h4">Contact# </span>
                                <span class="h5 float-right">{{$pending->distributorshop->ContactNumber}}</span>
                                <hr class="divider">
                            </span>

                            <span class="h3 d-block text-center">Subscription Details</span>
                            <hr class="divider">

                            <span class="d-block">
                                <span class="h4">Subscribed Package </span>
                                <span class="h5 float-right">{{$pending->distributorshop->subscription->package->PackageName}}</span>
                                <hr class="divider">
                            </span>

                            <span class="d-block">
                                <span class="h4">Transaction Id# </span>
                                <span class="h5 float-right">{{$pending->distributorshop->subscription->TransactionId}}</span>
                                <hr class="divider">
                            </span>

                            <span class="d-block">
                                <span class="h4">Payment Method </span>
                                <span class="h5 float-right">{{$pending->distributorshop->subscription->PaymentMethod}}</span>
                            </span>
                        @endif
                    </div>
                </div>
                <script>
                        //Custom JQuery Start

                        $(function(){
                            $('#detailbtn-{{$pending->id}}').click(function(){
                            console.log('Function Called');
                            var list = $('#list-{{$pending->id}}');
                                if(list.hasClass('d-none'))
                                {
                                    list.removeClass('d-none').addClass('d-flex');
                                }
                                else if (list.hasClass('d-flex'))
                                {
                                    list.removeClass('d-flex').addClass('d-none');
                                }
                            });
                        });

                        //Custom JQuery End
                </script>
            </div>
        @endforeach
    </div>

@endsection