routes/web.php
<?php

use App\Http\Controllers\AdminAuth\LoginController;;
use App\Http\Controllers\AdminControllers\AdminDashboardController;
use App\Http\Controllers\AdminControllers\AdminSettingController;
use App\Http\Controllers\AdminControllers\RequestController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CreditCardController;
use App\Http\Controllers\MedicineController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\InventorySearchController;
use App\Http\Controllers\MobileBankController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RequestController as FeedbackController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\ShopRegistrationController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\SubscriptionHistoryController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth', 'subcheck', 'noticount']], function () {

    //Retailer Specific Routes Start
    Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
    Route::put('/cart', [CartController::class, 'store']);
    Route::delete('/cart/{itemid}', [CartController::class, 'destroy'])->whereNumber('itemid')->name('cart.remove');

    Route::post('/inventory/search/retailer', [InventorySearchController::class, 'retailerInventorySearch'])->name('inventory.search.retailer');

    Route::get('/onlineorder', [OrderController::class, 'index'])->name('order.index');
    Route::get('/ordercheckout', [OrderController::class, 'create'])->name('order.checkout');
    Route::put('/ordercheckout', [OrderController::class, 'store']);
    Route::get('/quickorder/{medicineName}', [OrderController::class, 'quickOrder'])->name('order.quick');

    Route::get('/sales', [SaleController::class, 'index'])->name('sales.index');
    Route::get('/sales/newsale', [SaleController::class, 'create'])->name('sales.newsale');
    Route::post('/sales/newsale', [SaleController::class, 'store']);
    Route::post('/search', [SearchController::class, 'search']);
    //Retailer Specific Routes End

    //Distributor Specific Routes Start
    Route::post('order/status', [OrderController::class, 'update']);

    Route::post('/settings/mobileaccount', [SettingController::class, 'saveMobileAccountSettings'])->name('setting.mobileaccountsave');
    Route::delete('/settings/mobileaccount', [MobileBankController::class, 'destroy']);
    //Distributor Specific Routes End

    //Common Routes Start
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('/inventory', InventoryController::class);

    Route::get('/medicine/{id}/detail/{distributorid}', [MedicineController::class, 'show'])->whereNumber(['id', 'distributorid']);

    Route::get('/notifications', [NotificationController::class, 'index'])->name('notification.index');
    Route::put('/notification/read/{id}', [NotificationController::class, 'update'])->name('notification.read');
    Route::delete('/notification/delete/{id}', [NotificationController::class, 'destroy'])->name('notification.delete');

    Route::get('/order/history',[OrderController::class, 'show'])->name('orderhistory.show');

    Route::get('/reports', [ReportController::class, 'index'])->name('report.index');
    Route::post('/reports/daily', [ReportController::class, 'reportsByDaily'])->name('reports.daily');
    Route::post('/reports/weekly', [ReportController::class, 'reportsByWeekly'])->name('reports.weekly');
    Route::post('/reports/monthly', [ReportController::class, 'reportsByMonthly'])->name('reports.monthly');
    Route::post('/reports/yearly', [ReportController::class, 'reportsByYearly'])->name('reports.yearly');
    Route::resource('/request', FeedbackController::class)->except(['index', 'edit', 'destroy', 'update']);
    Route::put('/request/{id}', [FeedbackController::class, 'updateUser'])->name('request.update');

    Route::resource('/shopregistration', ShopRegistrationController::class);
    Route::resource('/subscription', SubscriptionController::class)->withoutMiddleware('subcheck')->middleware('subselect');
    Route::get('/subscriptionhistory', [SubscriptionHistoryController::class, 'index'])->withoutMiddleware('subcheck')->name('subscriptionhistory.index');
    Route::get('/settings', [SettingController::class, 'index'])->withoutMiddleware('subcheck')->name('settings.index');
    Route::post('/settings/api/token/regenerate', [SettingController::class, 'regenerateApiToken'])->name('api.token.regenerate');
    Route::post('/settings/shopaddress', [SettingController::class, 'updateShopAddress'])->name('setting.shopaddress');
    Route::post('/settings/reapplied', [SettingController::class, 'reapply'])->withoutMiddleware('subcheck')->name('settings.reapply');
    Route::post('/settings/changepassword', [SettingController::class, 'changePassword'])->name('settings.changepassword');
    Route::post('/settings/creditcard', [CreditCardController::class, 'update'])->name('settings.creditcard');
    Route::delete('/settings/creditcard', [CreditCardController::class, 'destroy']);
    Route::post('/settings/contactnumber', [SettingController::class, 'updateContactNumber'])->name('setting.contactnumber');
    //Common Routes End
});

//Defining Admin Routes
Route::prefix('/admin')->name('admin.')->group(function () {
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('/login', [LoginController::class, 'login']);

    Route::middleware(['auth:admin', 'noticount'])->group(function(){
        Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');

        Route::get('/medicine/create', [MedicineController::class, 'create'])->name('medicine.create');
        Route::post('/medicine/create', [MedicineController::class, 'store']);
        Route::get('/medicine', [MedicineController::class, 'index'])->name('medicine.index');
        Route::get('/medicine/edit/{id}', [MedicineController::class, 'edit'])->name('medicine.edit');
        Route::put('/medicine/edit/{id}', [MedicineController::class, 'update']);
        Route::delete('/medicine/delete/{id}', [MedicineController::class, 'destroy'])->name('medicine.delete');

        Route::get('/subscriptions', [SubscriptionController::class, 'adminindex'])->name('subscription.index');
        Route::get('/subscriptions/create', [SubscriptionController::class, 'create'])->name('subscription.create');
        Route::post('/subscriptions/create', [SubscriptionController::class, 'store']);
        Route::get('/subscriptions/edit/{id}', [SubscriptionController::class, 'edit'])->name('subscription.edit');
        Route::post('/subscriptions/edit/{id}', [SubscriptionController::class, 'adminUpdate']);

        Route::get('/pendingrequests', [RequestController::class, 'index'])->name('pending.index');
        Route::get('/feedbacks', [FeedbackController::class, 'index'])->name('feedback.index');
        Route::get('/feedback/{id}', [FeedbackController::class, 'show'])->name('feedback.show');
        Route::put('/feedback/{id}', [FeedbackController::class, 'update'])->name('feedback.update');
        Route::put('/feedback/{id}/completed', [FeedbackController::class, 'changeStatus'])->name('feedback.completed');
        Route::put('/request/accepted/{userid}', [RequestController::class, 'update'])->name('request.accepte');
        Route::delete('/request/rejected/{userid}', [RequestController::class, 'destroy'])->name('request.rejected');
        Route::get('/settings', [AdminSettingController::class, 'index'])->name('settings.index');
        Route::post('/settings/changepassword', [AdminSettingController::class, 'updatePassword'])->name('settings.changepassword');
        Route::post('/settings/mobileaccount', [AdminSettingController::class, 'saveMobileAccountSettings'])->name('settings.mobileaccountsave');
    });
});

?>

resources/views/testingViews/inventoryadd.blade.php
@extends('layouts.app')
@section('content')
<div class="jumbotron p-3">
    <div class="row">
        <div class="col-md-6">
            <span class="h1 d-block">Add New Medicines</span>
        </div>
        <div class="p-2 col-md-6 d-flex align-items-middle justify-content-end">
            <span class="mr-2">
                <a href="{{route('request.create')}}" class="btn btn-dark">Make a Request</a>
            </span>
            <span>
                <button id="btn-add-medicines" class="btn btn-success">Add Medicines</button>
            </span>
        </div>
    </div>
</div>
    <form method="POST" action="{{route('inventory.store')}}" id="form-main">
        @csrf
        @foreach ($medicines as $key => $medicine)
            <div class="jumbotron p-1 mb-1">
                <div class="card">
                    <div class="card-header h4">
                        <div class="row ">
                            <div class="col-md-6">{{$key}} <span class="num-body d-none">(<span class="num-text">0</span>)</span></div>
                            <div class="col-md-6">
                                <span class="float-right">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
                                        <path d="M7.247 11.14L2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                                    </svg>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="card-body d-none">
                        @foreach ($medicine as $med)
                            <div class="row p-1">
                                <div class="col-md-5">
                                    <span class="d-block h5">{{$med->MedicineName}} - {{$med->MedicineType}}</span>
                                    <span class="d-block h6 text-muted">{{implode(', ', json_decode($med->MedicineFormula))}}</span>
                                    <span class="d-block h6 text-muted">{{$med->MedicineCompany}}</span>
                                </div>
                                <div class="col-md-3">
                                    <input name="quantity" type="number" step="1" class="form-control d-block" placeholder="Quantity" value="0" pattern="[0-9]" min="0">
                                    <span class="d-block h6 text-muted mt-1">Quantity</span>
                                </div>
                                <div class="col-md-3">
                                    <input name="unitprice" type="number" step="0.5" class="form-control" placeholder="Unit Price" value="0" pattern="[0-9]" min="0">
                                    <span class="d-block h6 text-muted mt-1">Unit Price</span>
                                </div>
                                <div class="col-md-1 p-2">
                                    <input class="form-check-input ml-3" type="checkbox">
                                </div>
                                <input type="hidden" name="id" value="{{$med->MedicineId}}">
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        @endforeach
    </form>
@endsection

@section('scripts')
    <script>
        window.onload = function()
        {
            //Write Custom Jquery here

            var item_list = {};

            function addToList(ref)
            {
                var parent2 = $(ref).parent().parent();
                var key = parent2.find('input[name=id]').val();
                var quantity = parent2.find('input[name=quantity]').val();
                var unitprice = parent2.find('input[name=unitprice]').val();
                var item = [
                    quantity > 0 ? quantity : 0,
                    unitprice > 0 ? unitprice : 0
                ];
                item_list[key] = item;
            }

            function removeFromList(ref)
            {
                var parent2 = $(ref).parent().parent();
                var key = parent2.find('input[name=id]').val();
                delete item_list[key];
            }

            $('div.card-header').click(function(){
                var obj = $(this).next();
                if(obj.hasClass('d-none'))
                {
                    obj.removeClass('d-none').addClass('d-block');
                }
                else if (obj.hasClass('d-block'))
                {
                    obj.removeClass('d-block').addClass('d-none');
                }
            });

            $("input[type='checkbox']").click(function(){
                if($(this).is(':checked'))
                {
                    //Checked
                    var parent = $(this).parentsUntil('div.card')[2];
                    var count = parseInt($(parent).prev().find('span.num-text').text());
                    count += 1;
                    $(parent).prev().find('span.num-text').text(count);
                    var num_body = $(parent).prev().find('span.num-body');
                    if (num_body.hasClass('d-none') || count > 0)
                    {
                        num_body.removeClass('d-none').addClass('d-inline');
                    }
                    addToList(this);
                }
                else
                {
                    //Unchecked
                    var parent = $(this).parentsUntil('div.card')[2];
                    var count = parseInt($(parent).prev().find('span.num-text').text());
                    count -= 1;
                    $(parent).prev().find('span.num-text').text(count);
                    var num_body = $(parent).prev().find('span.num-body');
                    if (count <= 0)
                    {
                        num_body.removeClass('d-inline').addClass('d-none');
                    }
                    removeFromList(this);
                }
            });

            $('input[name=quantity], input[name=unitprice]').change(function(){
                if($(this).parent().parent().find('input[type=checkbox]').is(':checked'))
                {
                    removeFromList(this);
                    addToList(this);
                }
            });

            $('#btn-add-medicines').click(function(){
                if(Object.keys(item_list).length != 0)
                {
                    var form = $('#form-main');
                    var hidden_input = document.createElement('input');
                    $(hidden_input).attr('type', 'hidden').attr('name', 'medicine_list').attr('value', JSON.stringify(item_list));
                    form.append(hidden_input);
                    form.submit();
                }
                else
                {
                    alert('Please Select Medicine');
                }
            });
            //End of Custome JQuery
        }
    </script>
@endsection

resources/views/testingViews/inventoryedit.blade.php
@extends('layouts.app')
@section('content')
<div class="jumbotron p-3">
    <span class="h1 d-block">Update Medicine</span>
</div>
<form action="/inventory/{{$data->inventories[0]->InventoryId}}" method="POST">
    @method('PUT')
    @csrf
    <div class="container">
        <div class="row">
            <div class="col-xl-6">
                <div class="jumbotron p-1">
                    <div class="card">
                        <img src="/storage/medicines/{{$data->inventories[0]->medicine->MedicinePic}}">
                        <div class="card-body">
                            <span class="h5 d-block">{{$data->inventories[0]->medicine->MedicineName}} - {{$data->inventories[0]->medicine->MedicineType}}</span>
                            <span class="h6 d-block text-muted">By {{$data->inventories[0]->medicine->MedicineCompany}}</span>
                            <span class="h6 d-block text-muted">
                                Contains
                                @foreach (json_decode($data->inventories[0]->medicine->MedicineFormula) as $item)
                                    {{$item}},
                                @endforeach
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-6">
                <div class="jumbotron p-4">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                          <span class="input-group-text">Quantity</span>
                        </div>
                        <input name="quantity" id="quantity" type="number" class="form-control" min="1" value="{{$data->inventories[0]->Quantity}}" max="1000">
                      </div>

                      <div class="input-group mb-3">
                          <div class="input-group-prepend">
                              <span class="input-group-text">Unit Price</span>
                          </div>
                          <input name="unitprice" id="unitprice" type="number" step="any" class="form-control" value="{{$data->inventories[0]->UnitPrice}}" min="0" max="10000">
                      </div>
                </div>

                <div class="jumbotron p-4">
                    <span class="h1">Discription</span>
                    <p>{{$data->inventories[0]->medicine->MedicineDiscription}}</p>
                </div>

            </div>
        </div>
        <div class="row mb-1">
            <div class="col-xl-12">

                    <button class="btn btn-success" type="submit">Save Changes</button>

                <a class="btn btn-danger float-right" href="{{url()->previous()}}">Discard</a>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/testingViews/medicinedetail.blade.php
@extends('layouts.app')
@section('content')
    @include('navbars.navbar2')
    <div class="container">
        <div class="row">
            <div class="col-xl-6">
                <div class="jumbotron p-1">
                    <div class="card">
                        <img src="/storage/medicines/{{$data->MedicinePic}}">
                        <div class="card-body">
                            <span class="h5 d-block">{{$data->MedicineName}} - {{$data->MedicineType}}</span>
                            <span class="h6 d-block text-muted">By {{$data->MedicineCompany}}</span>
                            <span class="h6 d-block text-muted">{{$data->inventorydistributor->distributor->DistributorShopName}}</span>
                            <span class="h6 d-block text-muted">Contains {{implode(',', json_decode($data->MedicineFormula))}}</span>
                            <div>
                                <span><span id="unitprice">{{$data->inventorydistributor->UnitPrice}}</span>{{' PKR'}}</span>
                                <span class="float-right">In Stock {{$data->inventorydistributor->Quantity}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-6">
                <div class="jumbotron p-4">
                    <form method="POST" action="/cart">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="medicineid" value="{{$data->MedicineId}}">
                        <input type="hidden" name="distributorid" value="{{$data->inventorydistributor->distributor->DistributorShopId}}">
                        <input type="hidden" name="unitprice" value="{{$data->inventorydistributor->UnitPrice}}">
                    <div class="form-group">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Quantity</span>
                            </div>
                            <input id="quantity" name="quantity" type="number" class="form-control" min="1" max="{{$data->inventorydistributor->Quantity}}" value="1" required>
                          </div>

                          <div class="input-group mb-3">
                              <div class="input-group-prepend">
                                  <span class="input-group-text">Total Price</span>
                              </div>
                              <input id="totalprice" name="totalprice" type="number" class="form-control" readonly value="{{$data->inventorydistributor->UnitPrice}}" required>
                          </div>

                          <input id="btnaddtocart" type="submit" value="Add to Cart" class="form-control btn btn-success">
                    </div>
                    </form>
                </div>
                <div class="jumbotron p-4">
                    <span class="h1">Discription</span>
                    <p>{{$data->MedicineDiscription}}</p>
                </div>
            </div>
        </div>
        <script>
            //Custom JS to update total price as Quantity Increases or Decreases
            window.onload = function(){
                $('#quantity').on('change', function(){
                    var quantity = $('#quantity').val();
                    var unitprice = $('#unitprice').text();
                    $('#totalprice').val((quantity * unitprice).toFixed(2));
                });
            }
        </script>
    </div>
@endsection

resources/views/testingViews/subscriptionhistory.blade.php
@extends('layouts.app')
@section('content')
<div class="jumbotron p-3">
    <span class="h1 d-block">Subscription History</span>
</div>
    @if (count($data) > 0)
        @foreach ($data as $row)
            <div class="jumbotron p-3 mb-1">
            <div class="row p-1">
                <div class="col-md-3 text-center">
                    <span class="h5 d-block">{{$row->package->PackageName}}</span>
                    <span class="h6 d-block text-muted">Package Name</span>
                </div>
                <div class="col-md-3 text-center">
                    <span class="h5 d-block">{{$row->package->PackageDuration}}</span>
                    <span class="h6 d-block text-muted">Duration (Months)</span>
                </div>
                <div class="col-md-3 text-center">
                    <span class="h5 d-block">{{$row->startDate}}</span>
                    <span class="h6 d-block text-muted">Start Date</span>
                </div>
                <div class="col-md-3 text-center">
                    <span class="h5 d-block">{{$row->endDate}}</span>
                    <span class="h6 d-block text-muted">Ending Date</span>
                </div>
            </div>

                </div>
        @endforeach
    @else
        <p>No Record Found</p>
        <p>Click <a class="btn btn-success" href="{{route('subscription.index')}}">Here</a> to view offers and subscribe</p>
    @endif
@endsection