routes/web.php
<?php

use App\Http\Controllers\AdminAuth\LoginController;;
use App\Http\Controllers\AdminControllers\AdminDashboardController;
use App\Http\Controllers\AdminControllers\AdminSettingController;
use App\Http\Controllers\AdminControllers\RequestController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CreditCardController;
use App\Http\Controllers\MedicineController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\InventorySearchController;
use App\Http\Controllers\MobileBankController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RequestController as FeedbackController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\ShopRegistrationController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\SubscriptionHistoryController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth', 'subcheck', 'noticount']], function () {

    //Retailer Specific Routes Start
    Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
    Route::put('/cart', [CartController::class, 'store']);
    Route::delete('/cart/{itemid}', [CartController::class, 'destroy'])->whereNumber('itemid')->name('cart.remove');

    Route::post('/inventory/search/retailer', [InventorySearchController::class, 'retailerInventorySearch'])->name('inventory.search.retailer');

    Route::get('/onlineorder', [OrderController::class, 'index'])->name('order.index');
    Route::get('/ordercheckout', [OrderController::class, 'create'])->name('order.checkout');
    Route::put('/ordercheckout', [OrderController::class, 'store']);
    Route::get('/quickorder/{medicineName}', [OrderController::class, 'quickOrder'])->name('order.quick');

    Route::get('/sales', [SaleController::class, 'index'])->name('sales.index');
    Route::get('/sales/newsale', [SaleController::class, 'create'])->name('sales.newsale');
    Route::post('/sales/newsale', [SaleController::class, 'store']);
    Route::post('/search', [SearchController::class, 'search']);
    //Retailer Specific Routes End

    //Distributor Specific Routes Start
    Route::post('order/status', [OrderController::class, 'update']);

    Route::post('/settings/mobileaccount', [SettingController::class, 'saveMobileAccountSettings'])->name('setting.mobileaccountsave');
    Route::delete('/settings/mobileaccount', [MobileBankController::class, 'destroy']);
    //Distributor Specific Routes End

    //Common Routes Start
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('/inventory', InventoryController::class);

    Route::get('/medicine/{id}/detail/{distributorid}', [MedicineController::class, 'show'])->whereNumber(['id', 'distributorid']);

    Route::get('/notifications', [NotificationController::class, 'index'])->name('notification.index');
    Route::put('/notification/read/{id}', [NotificationController::class, 'update'])->name('notification.read');
    Route::delete('/notification/delete/{id}', [NotificationController::class, 'destroy'])->name('notification.delete');

    Route::get('/order/history',[OrderController::class, 'show'])->name('orderhistory.show');

    Route::get('/reports', [ReportController::class, 'index'])->name('report.index');
    Route::post('/reports/daily', [ReportController::class, 'reportsByDaily'])->name('reports.daily');
    Route::post('/reports/weekly', [ReportController::class, 'reportsByWeekly'])->name('reports.weekly');
    Route::post('/reports/monthly', [ReportController::class, 'reportsByMonthly'])->name('reports.monthly');
    Route::post('/reports/yearly', [ReportController::class, 'reportsByYearly'])->name('reports.yearly');
    Route::resource('/request', FeedbackController::class)->except(['index', 'edit', 'destroy', 'update']);
    Route::put('/request/{id}', [FeedbackController::class, 'updateUser'])->name('request.update');

    Route::resource('/shopregistration', ShopRegistrationController::class);
    Route::resource('/subscription', SubscriptionController::class)->withoutMiddleware('subcheck')->middleware('subselect');
    Route::get('/subscriptionhistory', [SubscriptionHistoryController::class, 'index'])->withoutMiddleware('subcheck')->name('subscriptionhistory.index');
    Route::get('/settings', [SettingController::class, 'index'])->withoutMiddleware('subcheck')->name('settings.index');
    Route::post('/settings/api/token/regenerate', [SettingController::class, 'regenerateApiToken'])->name('api.token.regenerate');
    Route::post('/settings/shopaddress', [SettingController::class, 'updateShopAddress'])->name('setting.shopaddress');
    Route::post('/settings/reapplied', [SettingController::class, 'reapply'])->withoutMiddleware('subcheck')->name('settings.reapply');
    Route::post('/settings/changepassword', [SettingController::class, 'changePassword'])->name('settings.changepassword');
    Route::post('/settings/creditcard', [CreditCardController::class, 'update'])->name('settings.creditcard');
    Route::delete('/settings/creditcard', [CreditCardController::class, 'destroy']);
    Route::post('/settings/contactnumber', [SettingController::class, 'updateContactNumber'])->name('setting.contactnumber');
    //Common Routes End
});

//Defining Admin Routes
Route::prefix('/admin')->name('admin.')->group(function () {
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('/login', [LoginController::class, 'login']);

    Route::middleware(['auth:admin', 'noticount'])->group(function(){
        Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');

        Route::get('/medicine/create', [MedicineController::class, 'create'])->name('medicine.create');
        Route::post('/medicine/create', [MedicineController::class, 'store']);
        Route::get('/medicine', [MedicineController::class, 'index'])->name('medicine.index');
        Route::get('/medicine/edit/{id}', [MedicineController::class, 'edit'])->name('medicine.edit');
        Route::put('/medicine/edit/{id}', [MedicineController::class, 'update']);
        Route::delete('/medicine/delete/{id}', [MedicineController::class, 'destroy'])->name('medicine.delete');

        Route::get('/subscriptions', [SubscriptionController::class, 'adminindex'])->name('subscription.index');
        Route::get('/subscriptions/create', [SubscriptionController::class, 'create'])->name('subscription.create');
        Route::post('/subscriptions/create', [SubscriptionController::class, 'store']);
        Route::get('/subscriptions/edit/{id}', [SubscriptionController::class, 'edit'])->name('subscription.edit');
        Route::post('/subscriptions/edit/{id}', [SubscriptionController::class, 'adminUpdate']);

        Route::get('/pendingrequests', [RequestController::class, 'index'])->name('pending.index');
        Route::get('/feedbacks', [FeedbackController::class, 'index'])->name('feedback.index');
        Route::get('/feedback/{id}', [FeedbackController::class, 'show'])->name('feedback.show');
        Route::put('/feedback/{id}', [FeedbackController::class, 'update'])->name('feedback.update');
        Route::put('/feedback/{id}/completed', [FeedbackController::class, 'changeStatus'])->name('feedback.completed');
        Route::put('/request/accepted/{userid}', [RequestController::class, 'update'])->name('request.accepte');
        Route::delete('/request/rejected/{userid}', [RequestController::class, 'destroy'])->name('request.rejected');
        Route::get('/settings', [AdminSettingController::class, 'index'])->name('settings.index');
        Route::post('/settings/changepassword', [AdminSettingController::class, 'updatePassword'])->name('settings.changepassword');
        Route::post('/settings/mobileaccount', [AdminSettingController::class, 'saveMobileAccountSettings'])->name('settings.mobileaccountsave');
    });
});

?>

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script type="text/javascript" src="{{ mix('js/app.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Bootstrap Icon CDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    {{-- Chart.js CDN --}}
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script> --}}
</head>
<body style="overflow: hidden">
    <div id="app" class="container-fluid h-100 pb-5 p-0 m-0">
        @include('navbars.adminmainhorizontalbar')
        <div class="row m-0 h-100 p-0">
              <div class="bg-dark border-right col-md-2 m-0 p-0">
                <div class="list-group list-group-flush d-none d-md-block">
                    {{-- If user is admin --}}
                    <a href="{{route('admin.dashboard')}}" class="list-group-item list-group-item-action bg-dark text-white">Dashboard</a>
                    <a href="{{route('admin.pending.index')}}" class="list-group-item list-group-item-action bg-dark text-white">Pending Requests @if(session('pendingcount') > 0)<span class="badge badge-success">{{session('pendingcount')}}</span>@endif</a>
                    <a href="{{route('admin.feedback.index')}}" class="list-group-item list-group-item-action bg-dark text-white">Feedbacks @if(session('feedbackcount') > 0)<span class="badge badge-success">{{session('feedbackcount')}}</span>@endif</a>
                    <a href="{{route('admin.medicine.index')}}" class="list-group-item list-group-item-action bg-dark text-white">Medicine</a>
                    <a href="{{route('admin.subscription.index')}}" class="list-group-item list-group-item-action bg-dark text-white">Subscription Packages</a>
                    <a href="{{route('admin.settings.index')}}" class="list-group-item list-group-item-action bg-dark text-white">Settings</a>
                  {{-- end --}}
                </div>
            </div>
            <div class="col-md-10 m-0 p-0 h-100">
                <div class="container-fluid overflow-auto p-1 m-0 h-100">
                    @include('inc.message')
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @yield('scripts')
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script type="text/javascript" src="{{ mix('js/app.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Bootstrap Icon CDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    {{-- Chart.js CDN --}}
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script> --}}
</head>
<body style="overflow: hidden">
    <div id="app" class="container-fluid h-100 pb-5 p-0 m-0">
        @include('navbars.mainhorizontalbar')
        <div class="row m-0 h-100 p-0">
            <div class="bg-dark border-right m-0 p-0 col-md-2">
                <div class="list-group list-group-flush d-none d-md-block">
                    @auth('web')
                        {{-- If user is normal --}}
                        <a href="/home" class="list-group-item list-group-item-action bg-dark text-white">Dashboard</a>
                        <a href="/inventory" class="list-group-item list-group-item-action bg-dark text-white">Inventory</a>
                        @user ('Retailer')
                            <a href="{{route('sales.index')}}" class="list-group-item list-group-item-action bg-dark text-white">Sales</a>
                            <a href="/onlineorder" class="list-group-item list-group-item-action bg-dark text-white">Online Order</a>
                        @elseuser('Distributor')
                        <a href="/order/history" class="list-group-item list-group-item-action bg-dark text-white">Orders</a>
                        @enduser
                        <a href="{{route('report.index')}}" class="list-group-item list-group-item-action bg-dark text-white">Reports</a>
                        @user ('Retailer')
                        <a href="/order/history" class="list-group-item list-group-item-action bg-dark text-white">Order History</a>
                        @enduser
                        <a href="/subscriptionhistory" class="list-group-item list-group-item-action bg-dark text-white">Subscription History</a>
                        <a href="{{route('notification.index')}}" class="list-group-item list-group-item-action bg-dark text-white">Notifications @if(session('notificationscount') > 0)<span class="badge badge-success">{{session('notificationscount')}}</span>@endif</a>
                        <a href="/settings" class="list-group-item list-group-item-action bg-dark text-white">Settings</a>
                    @endauth
                  {{-- end --}}
                </div>
            </div>
            <div class="col-md-10 m-0 p-0 h-100">
                <div class="container-fluid overflow-auto p-1 m-0 h-100">
                    @include('inc.message')
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @yield('scripts')
</body>
</html>

resources/views/layouts/app2.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    {{-- <script src="{{ asset('js/app.js') }}" defer></script> --}}
    <script type="text/javascript" src="{{ asset('js/app.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Bootstrap Icon CDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body style="overflow: hidden">
    <div id="app" class="container-fluid h-100 pb-5 p-0 m-0">
        @include('navbars.mainhorizontalbar')

        <div class="row m-0 h-100 p-0">
            <div class="col-md-12 m-0 p-0 h-100">
                <div class="container-fluid overflow-auto p-1 m-0 h-100">
                    @include('inc.message')
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
</body>
</html>